'use client';

import { useState } from 'react';

export default function NewChallengePage() {
  const [form, setForm] = useState({ challengeId: '', claimId: '', claimRevision: '1', counterexampleEvidenceId: '', rationale: '', requestedOutcome: 'refutes' });
  const [preview, setPreview] = useState(null);
  const [error, setError] = useState(null);
  const update = (key) => (event) => setForm((current) => ({ ...current, [key]: event.target.value }));
  function prepare(event) {
    event.preventDefault(); setError(null);
    if (Object.values(form).some((value) => !String(value).trim())) { setError('Challenge, target revision, counterexample Evidence, rationale, and outcome are required.'); setPreview(null); return; }
    setPreview({ ...form, claimRevision: Number(form.claimRevision) });
  }
  return <main className="mx-auto max-w-4xl px-6 py-16"><p className="text-sm font-bold uppercase tracking-[0.18em] text-destructive">Adversarial review</p><h1 className="mt-3 text-5xl font-semibold tracking-tight">Challenge a claim</h1><p className="mt-4 max-w-2xl text-muted-foreground">Lock a specific immutable Claim revision and attach counterexample Evidence for an auditable challenge.</p><form aria-label="Challenge form" onSubmit={prepare} className="mt-10 grid gap-4 rounded-xl border border-border bg-card p-6 md:grid-cols-2"><label className="grid gap-2 text-sm font-medium">Challenge ID<input required className="rounded border border-input bg-background p-3" value={form.challengeId} onChange={update('challengeId')} /></label><label className="grid gap-2 text-sm font-medium">Claim ID<input required className="rounded border border-input bg-background p-3" value={form.claimId} onChange={update('claimId')} /></label><label className="grid gap-2 text-sm font-medium">Target Claim revision<input required min="1" type="number" className="rounded border border-input bg-background p-3" value={form.claimRevision} onChange={update('claimRevision')} /></label><label className="grid gap-2 text-sm font-medium">Counterexample Evidence ID<input required className="rounded border border-input bg-background p-3" value={form.counterexampleEvidenceId} onChange={update('counterexampleEvidenceId')} /></label><label className="grid gap-2 text-sm font-medium md:col-span-2">Rationale<textarea required className="min-h-28 rounded border border-input bg-background p-3" value={form.rationale} onChange={update('rationale')} /></label><label className="grid gap-2 text-sm font-medium">Requested outcome<select className="rounded border border-input bg-background p-3" value={form.requestedOutcome} onChange={update('requestedOutcome')}><option value="refutes">Refutes</option><option value="qualifies">Qualifies</option></select></label><button className="w-fit rounded-md bg-primary px-4 py-2 text-primary-foreground" type="submit">Preview Challenge</button>{error && <p role="alert" className="text-sm text-destructive md:col-span-2">{error}</p>}</form>{preview && <section aria-label="Challenge preview" className="mt-8 rounded-xl border border-destructive/30 bg-destructive/5 p-6"><h2 className="text-2xl font-semibold">Challenge preview</h2><pre className="mt-4 overflow-x-auto rounded-lg bg-muted p-4 text-xs">{JSON.stringify(preview, null, 2)}</pre><p className="mt-4 text-sm text-muted-foreground">Submission will be enabled when the Challenge command endpoint is exposed.</p></section>}</main>;
}
