#!/usr/bin/env node
/**
 * Generate TypeScript declarations for the SDK from the API Edge OpenAPI document.
 * Usage: node scripts/generate-types.mjs [--check]
 *   default writes src/generated/types.d.ts
 *   --check compares against the checked-in file and exits non-zero on drift
 */
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const openapiPath = join(packageRoot, "..", "..", "apps", "api-edge", "openapi.json");
const outputPath = join(packageRoot, "src", "generated", "types.d.ts");

const document = JSON.parse(await readFile(openapiPath, "utf8"));

function schemaName(ref) {
  return ref.split("/").at(-1);
}

function mapType(schema) {
  if (!schema || typeof schema !== "object") return "unknown";
  if (schema.$ref) return schemaName(schema.$ref);
  if (schema.const !== undefined) return JSON.stringify(schema.const);
  if (Array.isArray(schema.enum)) return schema.enum.map((value) => JSON.stringify(value)).join(" | ");
  if (Array.isArray(schema.type)) return schema.type.map((type) => mapType({ ...schema, type })).join(" | ");
  switch (schema.type) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "array":
      return `${mapType(schema.items ?? {})}[]`;
    case "object": {
      const properties = schema.properties ?? {};
      const required = new Set(schema.required ?? []);
      const entries = Object.entries(properties);
      if (entries.length === 0) return "Record<string, unknown>";
      const fields = entries.map(([key, value]) => `${required.has(key) ? key : `${key}?`}: ${mapType(value)};`);
      return `{ ${fields.join(" ")} }`;
    }
    default:
      return "unknown";
  }
}

function interfaceName(name) {
  return name.replace(/[^A-Za-z0-9_]/g, "");
}

const lines = [];
lines.push("/**");
lines.push(" * Generated by packages/sdk-ts/scripts/generate-types.mjs from apps/api-edge/openapi.json.");
lines.push(` * API contract version: ${document.info.version}. Do not edit by hand.`);
lines.push(" */");
lines.push("");
lines.push("export type Json = string | number | boolean | null | Json[] | { [key: string]: Json };");
lines.push("");

for (const [name, schema] of Object.entries(document.components.schemas ?? {})) {
  lines.push(`export type ${interfaceName(name)} = ${mapType(schema)};`);
  lines.push("");
}

lines.push("export interface EviMeshOperations {");
for (const [path, operations] of Object.entries(document.paths)) {
  for (const [method, operation] of Object.entries(operations)) {
    if (method === "parameters" || typeof operation.operationId !== "string") continue;
    const secured = Array.isArray(operation.security) && operation.security.length > 0;
    lines.push(`  /** ${method.toUpperCase()} ${path}${secured ? " (bearer auth)" : ""} */`);
    lines.push(`  ${operation.operationId}: { method: ${JSON.stringify(method.toUpperCase())}; path: ${JSON.stringify(path)} };`);
  }
}
lines.push("}");
lines.push("");
lines.push("export type EviMeshOperationId = keyof EviMeshOperations;");
lines.push("");

const output = `${lines.join("\n").replace(/\n+$/, "")}\n`;

if (process.argv.includes("--check")) {
  const existing = await readFile(outputPath, "utf8").catch(() => null);
  if (existing !== output) {
    console.error("generated SDK types are out of date; run: node packages/sdk-ts/scripts/generate-types.mjs");
    process.exit(1);
  }
  console.log("generated SDK types match the OpenAPI contract");
} else {
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, output, "utf8");
  console.log(`wrote ${outputPath}`);
}
