name: Validate

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check whitespace errors
        run: git diff --check "$(git hash-object -t tree /dev/null)" HEAD
